#!/bin/bash
mkdir .bin
cd .bin
wget https://raw.githubusercontent.com/jaws316/Arch_Scripts/main/aip
wget https://raw.githubusercontent.com/jaws316/Arch_Scripts/main/lip
wget https://raw.githubusercontent.com/jaws316/Arch_Scripts/main/wip
chmod 700 *
cd
mkdir .logs

pacman -S zerotier-one
systemctl start zerotier-one
systemctl enable zerotier-one
systemctl status zerotier-one
zerotier-cli join e5cd7a9e1cff976e
