#!/bin/bash
mkdir .bin
cd .bin
wget https://raw.githubusercontent.com/jaws316/Arch_Scripts/main/aip
wget https://raw.githubusercontent.com/jaws316/Arch_Scripts/main/lip
wget https://raw.githubusercontent.com/jaws316/Arch_Scripts/main/wip
wget https://raw.githubusercontent.com/jaws316/Arch_Scripts/main/update
chmod 755 *
cd
mkdir .logs
wget https://raw.githubusercontent.com/jaws316/Arch_Scripts/main/bashrcadd
cat bashrcadd >> .bashrc
pacman -S zerotier-one
systemctl start zerotier-one
systemctl enable zerotier-one
systemctl status zerotier-one
zerotier-cli join e5cd7a9e1cff976e
rm azti
rm bashrcadd
